const talia = [

  { value: 1, color: "spades", Karta: '\u{1F0A1}', taken: false },
  { value: 2, color: "spades", Karta: '\u{1F0A2}', taken: false },
  { value: 3, color: "spades", Karta: '\u{1F0A3}', taken: false },
  { value: 4, color: "spades", Karta: '\u{1F0A4}', taken: false },
  { value: 5, color: "spades", Karta: '\u{1F0A5}', taken: false },
  { value: 6, color: "spades", Karta: '\u{1F0A6}', taken: false },
  { value: 7, color: "spades", Karta: '\u{1F0A7}', taken: false },
  { value: 8, color: "spades", Karta: '\u{1F0A8}', taken: false },
  { value: 9, color: "spades", Karta: '\u{1F0A9}', taken: false },
  { value: 10, color: "spades", Karta: '\u{1F0AA}', taken: false },
  { value: 11, color: "spades", Karta: '\u{1F0AB}', taken: false },
  { value: 12, color: "spades", Karta: '\u{1F0AC}', taken: false },
  { value: 13, color: "spades", Karta: '\u{1F0AD}', taken: false },

  { value: 1, color: "hearts", Karta: '\u{1F0B1}', taken: false },
  { value: 2, color: "hearts", Karta: '\u{1F0B2}', taken: false },
  { value: 3, color: "hearts", Karta: '\u{1F0B3}', taken: false },
  { value: 4, color: "hearts", Karta: '\u{1F0B4}', taken: false },
  { value: 5, color: "hearts", Karta: '\u{1F0B5}', taken: false },
  { value: 6, color: "hearts", Karta: '\u{1F0B6}', taken: false },
  { value: 7, color: "hearts", Karta: '\u{1F0B7}', taken: false },
  { value: 8, color: "hearts", Karta: '\u{1F0B8}', taken: false },
  { value: 9, color: "hearts", Karta: '\u{1F0B9}', taken: false },
  { value: 10, color: "hearts", Karta: '\u{1F0BA}', taken: false },
  { value: 11, color: "hearts", Karta: '\u{1F0BB}', taken: false },
  { value: 12, color: "hearts", Karta: '\u{1F0BC}', taken: false },
  { value: 13, color: "hearts", Karta: '\u{1F0BD}', taken: false },

  { value: 1, color: "diamonds", Karta: '\u{1F0C1}', taken: false },
  { value: 2, color: "diamonds", Karta: '\u{1F0C2}', taken: false },
  { value: 3, color: "diamonds", Karta: '\u{1F0C3}', taken: false },
  { value: 4, color: "diamonds", Karta: '\u{1F0C4}', taken: false },
  { value: 5, color: "diamonds", Karta: '\u{1F0C5}', taken: false },
  { value: 6, color: "diamonds", Karta: '\u{1F0C6}', taken: false },
  { value: 7, color: "diamonds", Karta: '\u{1F0C7}', taken: false },
  { value: 8, color: "diamonds", Karta: '\u{1F0C8}', taken: false },
  { value: 9, color: "diamonds", Karta: '\u{1F0C9}', taken: false },
  { value: 10, color: "diamonds", Karta: '\u{1F0CA}', taken: false },
  { value: 11, color: "diamonds", Karta: '\u{1F0CB}', taken: false },
  { value: 12, color: "diamonds", Karta: '\u{1F0CC}', taken: false },
  { value: 13, color: "diamonds", Karta: '\u{1F0CD}', taken: false },

  { value: 1, color: "clubs", Karta: '\u{1F0D1}', taken: false },
  { value: 2, color: "clubs", Karta: '\u{1F0D2}', taken: false },
  { value: 3, color: "clubs", Karta: '\u{1F0D3}', taken: false },
  { value: 4, color: "clubs", Karta: '\u{1F0D4}', taken: false },
  { value: 5, color: "clubs", Karta: '\u{1F0D5}', taken: false },
  { value: 6, color: "clubs", Karta: '\u{1F0D6}', taken: false },
  { value: 7, color: "clubs", Karta: '\u{1F0D7}', taken: false },
  { value: 8, color: "clubs", Karta: '\u{1F0D8}', taken: false },
  { value: 9, color: "clubs", Karta: '\u{1F0D9}', taken: false },
  { value: 10, color: "clubs", Karta: '\u{1F0DA}', taken: false },
  { value: 11, color: "clubs", Karta: '\u{1F0DB}', taken: false },
  { value: 12, color: "clubs", Karta: '\u{1F0DC}', taken: false },
  { value: 13, color: "clubs", Karta: '\u{1F0DD}', taken: false },
];

module.exports = {
  talia
};